<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personnel extends Model
{
    //
    protected $guarded = ['id'];

    public function matieres(){
        return $this->belongsToMany('App\Matiere','enseignes','personnel_id','matiere_id');
    }

    public function classes(){
        return $this->belongsToMany('App\Classe','interventions','personnel_id','classe_id');
    }

    public function interventions(){
        return $this->hasMany('App\Intervention');
    }

    public function cours(){
        return $this->hasMany('App\Cours');
    }

    public function classe(){
        return $this->hasOne(Classe::class);
    }

    public function user(){
        return $this->hasOne(User::class);
    }

    /*protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($per){
            User::create([
                'name'=>$per->nom_complet,
                'email'=>strtolower($per->nom).$per->id."@clp.com",
                'password'=>bcrypt("123456"),
                'personnel_id'=>$per->id,
                'role_id'=>10,



            ]);

        });

        self::deleted(function($delper){
            $user= User::where("personnel_id",$delper->id)->first();
            User::destroy($user->id);


        });



    }*/

}
